[book]
authors = ["Frank King"]
language = "zh"
multilingual = false
src = "src"
title = "Rust博客"

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/frank-king/rustblog-cn"
